name: christop corley
markdown: redcarpet
highlighter: pygments
timezone: America/Chicago
encoding: UTF-8
permalink: pretty
github_url: "https://github.com/cscorley"
twitter_url: "https://twitter.com/excsc"
email: "mailto:cscorley@gmail.com"
author_bio: |
    PhD student at <br />
    the
    <a href="http://cscorley.students.cs.ua.edu">University of Alabama</a>.
